# Generated by Django 4.0.4 on 2022-05-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apepat', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=200)),
                ('num', models.CharField(max_length=20)),
                ('colonia', models.CharField(max_length=200)),
                ('cp', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=11)),
                ('apemat', models.CharField(max_length=200)),
            ],
        ),
    ]
