# Generated by Django 4.0.4 on 2022-05-29 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0002_estatus_prospecto_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecto',
            name='estatus',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='prospectos.estatus'),
        ),
    ]
