# Generated by Django 4.0.4 on 2022-06-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0003_alter_prospecto_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecto',
            name='observaciones',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
