# Generated by Django 4.0.4 on 2022-06-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0004_prospecto_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecto',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
