# Generated by Django 4.0.4 on 2022-06-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0005_alter_prospecto_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecto',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
