# Generated by Django 4.0.4 on 2022-06-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0006_prospecto_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecto',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
